export const BACKEND_URL = 'http://localhost:3001';
export const USERS = '/users';
export const FEATURES = '/features';
export const PLANS = '/plans';
export const TAXES = '/taxes';
export const PAYMENTS = '/payments';
export const COUNTRIES = '/countries';
export const CREDIT_CARD = 'Credit Card';
export const PAYPAL = 'PayPal';